version: '3.1'

services:

  nginx:
    image: nginx
    volumes:
      - ./html/:/usr/share/nginx/html/:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      TZ: "Asia/Tokyo"

